name: Security

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'  # Weekly

permissions:
  contents: read

jobs:
  basic-security:
    name: Basic Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Basic security validation
        run: |
          echo "🔒 Running basic security checks"
          grep -r "password" . --exclude-dir=.git || echo "No hardcoded passwords found"
          grep -r "secret" . --exclude-dir=.git || echo "No hardcoded secrets found"
          echo "✅ Basic security check completed"

  file-security:
    name: File Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check file permissions
        run: |
          echo "🔍 Checking file permissions"
          find . -type f -perm /111 -not -path "./.git/*" || echo "No executable files found"
          echo "✅ File security check completed"
      
  summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [basic-security, file-security]
    if: always()
    steps:
      - name: Security summary
        run: |
          echo "🛡️ Security audit completed"
          echo "Basic Security: ${{ needs.basic-security.result }}"
          echo "File Security: ${{ needs.file-security.result }}"